package pojo;
// Generated Mar 30, 2015 11:13:48 AM by Hibernate Tools 3.6.0



/**
 * FriendshipId generated by hbm2java
 */
public class FriendshipId  implements java.io.Serializable {


     private long userId;
     private long friendId;

    public FriendshipId() {
    }

    public FriendshipId(long userId, long friendId) {
       this.userId = userId;
       this.friendId = friendId;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public long getFriendId() {
        return this.friendId;
    }
    
    public void setFriendId(long friendId) {
        this.friendId = friendId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FriendshipId) ) return false;
		 FriendshipId castOther = ( FriendshipId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getFriendId()==castOther.getFriendId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getUserId();
         result = 37 * result + (int) this.getFriendId();
         return result;
   }   


}


