package pojo;
// Generated Mar 30, 2015 11:13:48 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Long id;
     private String displayName;
     private String email;
     private String mobile;
     private String fullName;
     private String profileImage;
     private String password;
     private Boolean activated;
     private Boolean confirmed;
     private Set usersForBlockingId = new HashSet(0);
     private Set usersForBlockedId = new HashSet(0);
     private Set friendshipsForUserId = new HashSet(0);
     private Set friendshipsForFriendId = new HashSet(0);

    public User() {
    }

	
    public User(String mobile, String password) {
        this.mobile = mobile;
        this.password = password;
    }
    public User(String displayName, String email, String mobile, String fullName, String profileImage, String password, Boolean activated, Boolean confirmed, Set usersForBlockingId, Set usersForBlockedId, Set friendshipsForUserId, Set friendshipsForFriendId) {
       this.displayName = displayName;
       this.email = email;
       this.mobile = mobile;
       this.fullName = fullName;
       this.profileImage = profileImage;
       this.password = password;
       this.activated = activated;
       this.confirmed = confirmed;
       this.usersForBlockingId = usersForBlockingId;
       this.usersForBlockedId = usersForBlockedId;
       this.friendshipsForUserId = friendshipsForUserId;
       this.friendshipsForFriendId = friendshipsForFriendId;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }
    public String getFullName() {
        return this.fullName;
    }
    
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }
    public String getProfileImage() {
        return this.profileImage;
    }
    
    public void setProfileImage(String profileImage) {
        this.profileImage = profileImage;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getActivated() {
        return this.activated;
    }
    
    public void setActivated(Boolean activated) {
        this.activated = activated;
    }
    public Boolean getConfirmed() {
        return this.confirmed;
    }
    
    public void setConfirmed(Boolean confirmed) {
        this.confirmed = confirmed;
    }
    public Set getUsersForBlockingId() {
        return this.usersForBlockingId;
    }
    
    public void setUsersForBlockingId(Set usersForBlockingId) {
        this.usersForBlockingId = usersForBlockingId;
    }
    public Set getUsersForBlockedId() {
        return this.usersForBlockedId;
    }
    
    public void setUsersForBlockedId(Set usersForBlockedId) {
        this.usersForBlockedId = usersForBlockedId;
    }
    public Set getFriendshipsForUserId() {
        return this.friendshipsForUserId;
    }
    
    public void setFriendshipsForUserId(Set friendshipsForUserId) {
        this.friendshipsForUserId = friendshipsForUserId;
    }
    public Set getFriendshipsForFriendId() {
        return this.friendshipsForFriendId;
    }
    
    public void setFriendshipsForFriendId(Set friendshipsForFriendId) {
        this.friendshipsForFriendId = friendshipsForFriendId;
    }




}


